/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tdd;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

import common.Define;
import common.Folder;
import common.FolderControl;
import yaml.YamlControl;

public class App {

	public static void main(String[] args) throws IOException {

		Folder folder = YamlControl.yamlRead(Define.getloadPath());

		ScheduledExecutorService sche = Executors.newScheduledThreadPool(2);

		sche.scheduleAtFixedRate(() -> {
			try {
				inputFolderCheck(folder);
			} catch (IOException e) {
				System.out.println("フォルダ監視処理でエラーが発生しました。");
			}
		}, 0L, 5L, TimeUnit.SECONDS);

		sche.scheduleAtFixedRate(() -> {
			try {
				outputFolderCheck(folder);
			} catch (IOException e) {
				System.out.println("フォルダ監視処理でエラーが発生しました。");
			}
		}, 0L, 5L, TimeUnit.SECONDS);
	}

	/**
	 * inputフォルダ監視
	 * @param folder：Folderクラスのインスタンス
	 * @throws IOException
	 */
	public static void inputFolderCheck(Folder folder) throws IOException {

		Files.list(Paths.get(folder.getInDirectory())).filter(Files::isRegularFile).forEach(p -> {
			if (p.equals(null)) {
				return;
			} else {
				// inputフォルダにファイルを移す処理
				try {
					FolderControl.inToInput(p, Paths.get(folder.getInputDirectory()), p.getFileName());
				} catch (IOException e) {
					System.out.println("INフォルダのファイル制御に失敗しました。");
				}
			}
		});
	}

	/**
	 * outフォルダ監視
	 * @param folder：Folderクラスのインスタンス
	 * @throws IOException
	 */
	public static void outputFolderCheck(Folder folder) throws IOException {

		Files.list(Paths.get(folder.getOutDirectory())).filter(Files::isRegularFile).forEach(p -> {
			if (p.equals(null)) {
				return;
			} else {
				// outputフォルダにファイルを移す処理
				try {
					if (!FolderControl.errXmlCheck(p.getFileName().toString(), Define.getErrorPath())) {
						FolderControl.deleteFile(p);
					} else {
						FolderControl.inToInput(p, Paths.get(folder.getOutputDirectory()), p.getFileName());
					}
				} catch (IOException e) {
					System.out.println("OUTフォルダのファイル制御に失敗しました。");
				}
			}
		});
	}
}